ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS vin TEXT,
  ADD COLUMN IF NOT EXISTS vehicle_trim TEXT,
  ADD COLUMN IF NOT EXISTS body_style TEXT,
  ADD COLUMN IF NOT EXISTS dol INTEGER,
  ADD COLUMN IF NOT EXISTS last_price NUMERIC,
  ADD COLUMN IF NOT EXISTS lotlinx_vdp INTEGER,
  ADD COLUMN IF NOT EXISTS total_vdp INTEGER,
  ADD COLUMN IF NOT EXISTS net_new_shoppers INTEGER,
  ADD COLUMN IF NOT EXISTS pct_sales_opps_since_campaign NUMERIC;